version: 2.1

orbs:
  cypress: cypress-io/cypress@1.17.1

workflows:
  build:    
    jobs:
      - cypress/install
      - cypress/run:
          pre-steps:
            - run: |
                echo 'export CYPRESS_RECORD_KEY=$(cat 0e47833d-a73f-4f3d-a6d8-ab2f26a77645)' >> $BASH_ENV
          name: firefox
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          browser: firefox
          group: firefox
          store_artifacts: true
      - cypress/run:
          pre-steps:
            - run: |
                echo 'export CYPRESS_RECORD_KEY=$(cat 0e47833d-a73f-4f3d-a6d8-ab2f26a77645)' >> $BASH_ENV
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          browser: chrome
          group: chrome
          store_artifacts: true