version: 2.1

orbs:
  cypress: cypress-io/cypress@1.17.1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: firefox
          requires:
            - cypress/install
          executor: cypress/browsers:node12.8.1-chrome80-ff72
          record: true
          browser: firefox
          group: firefox
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers:node12.8.1-chrome80-ff72
          record: true
          browser: chrome
          group: chrome
      
      - store_artifacts:
          path: cypress/videos
